#!/bin/bash
#PBS -N SMR
#PBS -l nodes=cu04:ppn=6
#PBS -e SMR.err
#PBS -o SMR.log
#PBS -q batch
#PBS -V

SMR_input_dir='/public/jiangjw/02.anxiety_ADs_EUR/09.SMR/Github_code_test' #modify into your path
eQTL_dir='/public/jiangjw/02.anxiety_ADs_EUR/09.SMR/eQTL_data' #modify into your path
reference_dir='/public/jiangjw/reference/g1000_eur' #modify into your path
run_dir='/public/jiangjw/02.anxiety_ADs_EUR/09.SMR/smr-1.3.1-linux-x86_64' #modify into your path
result_dir='/public/jiangjw/02.anxiety_ADs_EUR/09.SMR/Github_code_test' #modify into your path

phenos=("Anxiety2021" "DiagnosedAR")
tissue=("Brain_Frontal_Cortex_BA9") #you can choose tissue according to results of tissue-specific SNP heritability enrichment analysis

for i in ${phenos[@]};
do
	for j in ${tissue[@]};
	do
		${run_dir}/smr --bfile ${reference_dir}/g1000_eur --gwas-summary ${SMR_input_dir}/${i}_SMR.clean.txt --beqtl-summary ${eQTL_dir}/${j} --maf 0.01 --out ${result_dir}/${i}_${j} --thread-num 10
	done
done


