#/bin/bash
#PBS -N clump_p5e6
#PBS -l nodes=cu04:ppn=3
#PBS -e clump_p5e6.err
#PBS -o clump_p5e6.log
#PBS -q batch
#PBS -V

run_plink_dir="/public/jiangjw/plink" #modify into your path
ref_file="/public/jiangjw/reference/g1000_eur"  #modify into your path
GWAS_sumstats_dir="/public/jiangjw/GWAS_sumstats/EUR" #modify into your path
result_dir='/public/jiangjw/02.anxiety_ADs_EUR/01.MR/Github_code_test/Hema_ImmuneCell_Diseases_MR' #modify into your path

p1="0.000005"
p2="1"
r2="0.1"
kb="1000"

phenos=("Anxiety2021" "DiagnosedAR" "BASO" "CD19" "CD3" "CD4CD8ratio" "CD4" "CD56" "CD8" "EOS" "HB" "HT" "LYMPH" "MCHC" "MCH" "MCV" "MONO" "NEUT" "PLT" "RBC" "WBC")

for i in ${phenos[@]}; do
	${run_plink_dir}/plink \
		--bfile ${ref_file}/g1000_eur \
		--clump-snp-field rsid \
		--clump-field p \
		--clump-p1 ${p1} \
		--clump-p2 ${p2} \
		--clump-r2 ${r2} \
		--clump-kb ${kb} \
		--clump ${GWAS_sumstats_dir}/${i}.clean.txt \
		--out ${result_dir}/${i}.LD_result
done

